- lib/components/create_join_dialog.dart
- pubspec.lock
- pubspec.yaml
Moved from obsolete flutter_duration_picker to duration_picker
(and a couple of spacing issues :)   ).
> Replace duration picker and version update

- lib/components/create_join_dialog.dart
- lib/components/dialog_boxes.dart
- lib/main.dart
- lib/views/home.dart
- pubspec.lock
- pubspec.yaml
Fixes #16 
Used package sizer to fix the alignment and not used constant height and width values, but dynamically calculated ones from sizer.
> [Sizer] Misaligned button fix on dialogue boxes.

- lib/components/create_join_dialog.dart
- lib/services/database_mutation_functions.dart
- lib/services/shared_preference_service.dart
- lib/services/user_config.dart
- lib/view_model/auth_screen_model.dart
- lib/view_model/hike_screen_model.dart
- lib/view_model/home_view_model.dart
- lib/views/auth_screen.dart
Fixes #41 
Refactored some code so that flutter analyze would complete without errors and CI does not fail.
> rfrac: removed errors which caused flutter analyze to fail.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> Templates introduced

- lib/components/create_join_dialog.dart
- lib/components/dialog_boxes.dart
- lib/components/hike_screen_widget.dart
- lib/views/auth_screen.dart
- lib/views/hike_screen.dart
- lib/views/home.dart
Fixes #54 
Describe the changes you have made in this PR - 
**Added an exit pop confirmation box for the home and auth screen.**
Also, added a rounded border for all dialog boxes to give a more maintained and premium look!
Screenshots of the changes (If any) -
> Exit Popbox and Rounded-Borders

- lib/services/database_mutation_functions.dart
- lib/utilities/constants.dart
- lib/view_model/auth_screen_model.dart
Fixes #70 
Describe the changes you have made in this PR - Changed return type from bool to String to display particular errors better instead of repeated and unclarified errors.
https://user-images.githubusercontent.com/69353350/150198408-0574450d-b32d-4673-82f4-43b0c0a48543.mov
> Multiple error messages resolved

- lib/services/database_mutation_functions.dart
Fixes #76 
Describe the changes you have made in this PR - Instead of adding to the end of the list, inserted at the start.
> Reversed list according to recent

- lib/components/beacon_card.dart
- lib/components/create_join_dialog.dart
- lib/view_model/home_view_model.dart
Fixes #79 
Describe the changes you have made in this PR - Changed random inputs into uppercase for easy interference
https://user-images.githubusercontent.com/69353350/150634971-ffb99542-cf69-4ac7-ae7f-ab100cf26d8c.mov
> Passkey Capitalisation

- lib/components/active_beacon.dart
- lib/components/beacon_card.dart
- lib/components/timer.dart
- lib/utilities/constants.dart
- pubspec.yaml
Fixes #84 
Fixes #90 
Describe the changes you have made in this PR - Added different colors for different timed beacons and a countdown timer for pre scheduled beacons.
> Changed card colors, added status for different beacons + feat:countdown timer for pre-scheduled beacons

- lib/views/hike_screen.dart
Fixes #75 
Describe the changes you have made in this PR - Removed custom paint and added floating button for going back.
> Improved hike screen UI

- pubspec.lock
- pubspec.yaml
Describe the changes you have made in this PR - Updated dependencies and sorted them for better documentation in pubspec.yaml. Also added updated pubspeck.lock file after latest commit
> Updated  and sorted dependencies

- lib/components/create_join_dialog.dart
Fixes #92 
Describe the changes you have made in this PR - Reduced font size for time picker and changed theme of date and time picker according to the theme of app
> Reduced font size and changed themes

- lib/components/create_join_dialog.dart
Fixes #95 
Describe the changes you have made in this PR - Fixed keyboard bug on create hike box. No clicking anywhere else on dialog box, except text field, would close the keyboard.
> feat: Close keyboard when text field is out of focus

- lib/views/auth_screen.dart
- lib/views/hike_screen.dart
Fixes #104 
Describe the changes you have made in this PR - Increased distance between buttons on the hike screen for smaller screen sizes
> Increased distance between buttons for smaller screen sizes

- lib/services/database_mutation_functions.dart
Fixes #98 
Describe the changes you have made in this PR - Added preference to show active beacons earlier than upcoming ones in nearby beacons. Also added some commas.
> feat: nearby beacon list according to start time

- lib/components/beacon_card.dart
- lib/components/timer.dart
- lib/services/navigation_service.dart
Fixes #100 
Describe the changes you have made in this PR - Added functionality for post-activation notifying snackbar for clicking and joining hike. Also, improved general snackbar look for whole app.
> Snackbar functionality added and general UI improved

- lib/views/home.dart
Fixed #108
Added a loading indicator on both nearby beacon and your beacon widget
<p float="left">
</p>
> added loading indicator on both nearby beacon widget and your beacon

- lib/main.dart
- lib/services/local_notification.dart
Fixes #52 
Describe the changes you have made in this PR - Added a notification to remind users 1 hour prior to a hike starting and changed notification messages. Now users could be reminded beforehand about a pre-scheduled hike starting.
> Feature: Added reminder for a hike about to start in an hour

- lib/components/hike_screen_widget.dart
- lib/locator.dart
- lib/main.dart
- lib/services/connection_checker.dart
- lib/services/database_mutation_functions.dart
- lib/services/hive_localdb.dart
- lib/services/user_config.dart
- lib/splash_screen.dart
- lib/view_model/hike_screen_model.dart
- lib/view_model/home_view_model.dart
- pubspec.lock
- pubspec.yaml
Fixes #3 
Describe the changes you have made in this PR -
Used Hive local Db to fetch data (if any) if internet is not available.
> feat: Maintain State when network is lost

- lib/view_model/hike_screen_model.dart
- lib/views/hike_screen.dart
- pubspec.lock
- pubspec.yaml
Fixes #117 
Describe the changes you have made in this PR - Animated google map markers and added a ripple effect for current location marker for better UX.
> Feature: Animated Google map markers.

- .env.example
- android/app/src/main/AndroidManifest.xml
- ios/Runner/AppDelegate.swift
- lib/config/environment_config.dart
- lib/main.dart
- lib/services/graphql_config.dart
- lib/view_model/hike_screen_model.dart
Fixes #135 
Describe the changes you have made in this PR -
Hello Everyone In this PR I have made a few changes related to environment variables. I have bit structure the code and also added Env variable support for IOS google Maps API Key as there will be different API keys available for  Android and IOS.
Screenshots of the changes (If any) -
Cc:   @nb9960   @cfsmp3  @Aadeesh11 @ItsAdityaKSingh
> Add  Environment config file 

- README.md
- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- pubspec.lock
- pubspec.yaml
Fixes #118 
Describe the changes you have made in this PR - Updated files to run on the new Flutter release without any errors. Also, updated dependencies.
> Updated compilesdkVersion to support Flutter 2.10 + updated dependencies and pubspec files

- lib/views/auth_screen.dart
Minor code optimization, create a separate  widget for spacing
>  created seperate widget for spacing

- lib/components/create_join_dialog.dart
- lib/view_model/home_view_model.dart
- lib/views/home.dart
Fixes #120 
Describe the changes you have made in this PR - Initialised fetching of the list elements and added function to reload whenever a new beacon is created or joined.
> Fixes: Multiple list reloads whenever TextField is focussed

- lib/view_model/auth_screen_model.dart
- lib/views/auth_screen.dart
> Worked on issue #162 Automated the redundancy removal from email entered by the user

- .github/workflows/flutter-ci.yml
- pubspec.lock
- pubspec.yaml
Describe the changes you have made in this PR - Made changes for smooth updation into Flutter v3.0
> Changes for Flutter 3.0

- lib/components/loading_screen.dart
- lib/views/home.dart
- pubspec.lock
Also, pubspec.lock changes updated
> Resolved formatting issues in pipeline

- pubspec.lock
- pubspec.yaml
Fixes #171 
Describe the changes you have made in this PR - Downgraded plugin version as the latest plugin was not rendering the map as required.
Also, few changes due to the flutter upgrade.
> Fixes: Map error on hike screen

- lib/main.dart
Fixes #207 
Just had to put await before localNotif.initialize(); so the function runs completely before moving further.
> resolved local notification exception.

- .github/workflows/flutter-ci.yml
- .gitignore
- android/app/build.gradle
- android/build.gradle
- lib/main.dart
- pubspec.lock
- pubspec.yaml
Fixes #253
Describe the changes you have made in this PR -
I added firebase configuration for google signin
Screenshots of the changes (If any) -
> Fix-253: fixed google signin
